from commands.cmd_updatelog import *
from commands.cmd_geguide import *
from commands.cmd_launchbot import *
from commands.cmd_start import *
from commands.cmd_wantpokemon import *
from commands.cmd_my903 import *
from commands.cmd_pin import *
from commands.cmd_help import *
from commands.cmd_crypto import *
from commands.cmd_css import *
from commands.cmd_su import *
from commands.cmd_cityuinfo import *
from commands.cmd_cbc import *
from commands.cmd_edb import *
